version: "3.7"

services:
  cateat_db:
    container_name: postgres
    image: "postgres:12.10-alpine"
    restart: on-failure
    ports:
      - "5432:5432"
    env_file: ./conf/.env
    networks:
      - app

  api_service:
    container_name: backend_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - cateat_db
    links:
      - cateat_db:postgres
    tty: true
    stdin_open: true
    env_file: ./conf/.env
    networks:
      - app

  frontend:
    container_name: cat-monitoring
    build:
      context: ./cat-monitoring
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api_service
    networks:
      - app

networks:
  app:
    driver: bridge